function conditionsNote(m){
 const en=ATLAS_LANGUAGE==='en';
 const coverage=({Completa:en?'complete coverage':'cobertura completa',Parcial:en?'partial coverage':'cobertura parcial',Insuficiente:en?'insufficient coverage':'cobertura insuficiente'})[m.condicoesCobertura]||'';
 return `${m.condicoesDisponiveis??0}/4 ${en?'indicators available':'indicadores disponíveis'} · ${coverage}. ${en?'See the classification rules below.':'Veja os critérios abaixo.'}`;
}
function conditionsMethodDetails(m){
 const en=ATLAS_LANGUAGE==='en',method=ATLAS_CONDITIONS_METHOD;
 const unitNumber=v=>new Intl.NumberFormat(ATLAS_LANGUAGE,{maximumFractionDigits:4}).format(v);
 const drought=method.drought_percent_years_by_biome[m.bioma];
 const droughtText=m.reference?(en?'Biome-specific thresholds in the table below':'Limites por bioma na tabela abaixo'):drought?`${unitNumber(drought.p50)}% / ${unitNumber(drought.p75)}% (${en?'years':'anos'}; n=${drought.n})`:(en?'No observed reference for this biome; drought contributes no points.':'Sem referência observada neste bioma; seca não soma pontos.');
 return `<details class="conditions-method"><summary>${en?'How enabling conditions are classified':'Como as condições são classificadas'}</summary><p>${en?'Comparative municipal screening, with fixed thresholds for the 11 September 2026 edition. Lower market distance and lower drought frequency receive higher scores.':'Triagem comparativa municipal, com limites fixos na edição de 11 de setembro de 2026. Menor distância ao mercado e menor frequência de seca recebem mais pontos.'}</p><ul><li>${en?'Market distance (national reference):':'Distância ao mercado (referência nacional):'} ≤ ${unitNumber(method.market_km.p50)} km = 100; > ${unitNumber(method.market_km.p50)} ${en?'to':'até'} ${unitNumber(method.market_km.p75)} km = 50; > ${unitNumber(method.market_km.p75)} km = 0.</li><li>${en?'Drought in this biome, P50 / P75:':'Seca neste bioma, P50 / P75:'} ${droughtText}. ${en?'At or below P50: 100; above P50 to P75: 50; above P75: 0.':'Até P50: 100; acima de P50 até P75: 50; acima de P75: 0.'}</li><li>${en?'Extension and education retain the existing documented scores (0, 50 or 100). Credit is not included in this class.':'Assistência e escolaridade mantêm os pontos das regras documentadas (0, 50 ou 100). Crédito não integra esta classe.'}</li></ul><p><strong>${en?'Formula':'Fórmula'}:</strong> (${en?'drought + extension + education':'seca + assistência + escolaridade'}) × ${en?'market':'mercado'} / 100. ${en?'Adequate >240; intermediate 150–240; limited <150.':'Adequadas >240; intermediárias 150–240; limitadas <150.'}</p><p>${en?'A missing support indicator adds no points and makes coverage partial. Missing market data or all support data leaves the municipality unclassified. Drought values imputed from biome medians are excluded. Thresholds are comparative, not agronomic or transport viability limits.':'Um suporte ausente não soma pontos e torna a cobertura parcial. Sem mercado ou sem todos os suportes, o município fica sem classificação. Valores de seca imputados pela mediana do bioma são excluídos. Os limites são comparativos, não limites agronômicos ou de viabilidade de transporte.'}</p><p>${en?'Method':'Método'}: ${method.version}${m.condicoesDisponiveis!==undefined?` · ${en?'Available indicators':'Indicadores disponíveis'}: ${m.condicoesDisponiveis}/4`:''}.</p></details>`;
}
function conditionsReferenceHtml(){
 const en=ATLAS_LANGUAGE==='en',config=ATLAS_CONDITIONS_METHOD;
 const format=v=>new Intl.NumberFormat(ATLAS_LANGUAGE,{maximumFractionDigits:4}).format(v);
 const rows=Object.entries(config.drought_percent_years_by_biome).map(([biome,t])=>`<tr><td>${biome}</td><td>${format(t.p50)}%</td><td>${format(t.p75)}%</td><td>${t.n}</td></tr>`).join('');
 return `<h3>${en?'Enabling conditions: methodology defined for this edition':'Condições para produzir: metodologia definida nesta edição'}</h3>${conditionsMethodDetails({reference:true})}<div class="atlas-query-table-wrap"><table class="data-table"><thead><tr><th>${en?'Drought reference biome':'Bioma de referência da seca'}</th><th>P50 (% ${en?'of years':'dos anos'})</th><th>P75 (% ${en?'of years':'dos anos'})</th><th>n</th></tr></thead><tbody>${rows}</tbody></table></div><p>${en?'The Pampa has no directly observed municipal drought reference in this snapshot. The Pantanal reference has only 8 municipalities and must be interpreted cautiously. Displayed thresholds are rounded; the JSON contains the exact limits.':'O Pampa não possui referência municipal de seca diretamente observada nesta base. A referência do Pantanal tem apenas 8 municípios e exige cautela na interpretação. Os limites exibidos são arredondados; o JSON contém os valores exatos.'}</p><p><a href="conditions_methodology_${en?'en':'pt'}.md">${en?'Full methodology':'Metodologia completa'}</a> · <a href="conditions_methodology.json">${en?'Exact thresholds and version':'Limites exatos e versão'}</a></p>`;
}
